"""Multi-factor stock selection strategy (多因子选股策略).

Core strategy implementing IC-weighted multi-factor composite scoring
with industry and size neutralization.

Based on Zhu Yifeng (2025) and broker research (QuantsPlaybook).
"""

import logging

import numpy as np
import pandas as pd

from quantsys.strategies.base import BaseStrategy
from quantsys.factors.registry import FactorRegistry
from quantsys.factors.processor import FactorProcessor
from quantsys.factors.neutralizer import FactorNeutralizer

logger = logging.getLogger(__name__)


class MultiFactorStrategy(BaseStrategy):
    """Multi-factor stock selection strategy.

    Process:
    1. Compute all enabled factors on the universe
    2. Winsorize, standardize, and neutralize each factor
    3. Combine factors using IC-IR weighted average
    4. Select top N% of stocks by composite score

    Config options:
        top_n_pct: Select top N% stocks (default 0.20)
        factor_weights: 'ic_ir', 'equal', or 'manual'
        weights_path: Path to IC-IR weights file (CSV/Parquet/JSON with
                      factor/weight columns), generated by
                      scripts/evaluate_factors.py --save-weights
        manual_weights: {factor_name: weight} dict when factor_weights='manual'
        neutralization: List of ['industry', 'size']
        weighting: 'equal_weight' or 'market_cap'
    """

    name = "multifactor"

    def __init__(self, config: dict = None, cache_dir: str = None):
        super().__init__(config, cache_dir)
        self.registry = FactorRegistry()
        self.registry.discover()
        self.processor = FactorProcessor()
        self.neutralizer = FactorNeutralizer()
        self._ic_weights = self._load_ic_weights()

    # -- IC-IR weight loading ---------------------------------------------

    def _load_ic_weights(self) -> pd.Series | None:
        """Load IC-IR weights produced by scripts/evaluate_factors.py.

        Resolution order:
            1. ``multifactor.factor_weights: "manual"`` + ``manual_weights``
               dict {factor_name: weight} inline in config.
            2. ``multifactor.weights_path`` pointing at a CSV/Parquet/JSON
               file with columns (factor, weight) — typically generated by
               ``scripts/evaluate_factors.py --save-weights``.
            3. None → caller falls back to equal weight (legacy behavior).
        """
        config = self.config.get("multifactor", {})

        if config.get("factor_weights") == "manual":
            manual = config.get("manual_weights") or {}
            if manual:
                return pd.Series({k: float(v) for k, v in manual.items()})

        if config.get("factor_weights") != "ic_ir":
            return None

        path = config.get("weights_path", "")
        if not path:
            return None

        from pathlib import Path
        p = Path(path)
        if not p.exists():
            logger.warning(f"IC-IR weights file not found: {p}, falling back to equal weight")
            return None

        try:
            if p.suffix == ".parquet":
                df = pd.read_parquet(p)
            elif p.suffix == ".json":
                df = pd.read_json(p)
            else:
                df = pd.read_csv(p)
            if "factor" not in df.columns or "weight" not in df.columns:
                logger.warning(f"weights file {p} lacks factor/weight columns")
                return None
            weights = df.set_index("factor")["weight"].astype(float)
            weights = weights[weights > 0]  # long-only: drop non-positive alpha
            if weights.empty:
                return None
            return weights / weights.sum()
        except Exception as e:
            logger.warning(f"Failed to load IC-IR weights from {p}: {e}")
            return None

    def _resolve_weights(self, columns: list[str]) -> pd.Series:
        """Align loaded IC-IR weights to the actually-computed factors."""
        if self._ic_weights is None:
            return pd.Series(1.0 / len(columns), index=columns)

        aligned = self._ic_weights.reindex(columns).fillna(0.0)
        if aligned.sum() <= 0:
            logger.warning("No IC-IR weights matched computed factors; equal weight fallback")
            return pd.Series(1.0 / len(columns), index=columns)

        aligned = aligned / aligned.sum()
        logger.debug(
            "Using IC-IR weights: "
            + ", ".join(f"{k}={v:.2f}" for k, v in aligned[aligned > 0].items())
        )
        return aligned

    def _find_nearest_date(self, dates: pd.DatetimeIndex, target: pd.Timestamp) -> pd.Timestamp:
        """Find the nearest previous date <= target in an index."""
        valid = dates[dates <= target]
        if len(valid) == 0:
            return None
        return valid[-1]

    def generate_signals(
        self, universe: list[str], date: str
    ) -> pd.Series:
        """Generate buy signals as position weights.

        Args:
            universe: List of stock codes.
            date: Reference date as 'YYYY-MM-DD'.

        Returns:
            Series mapping symbol -> target weight.
        """
        if not universe:
            return pd.Series(dtype=float)

        config = self.config.get("multifactor", {})
        top_pct = config.get("top_n_pct", 0.20)
        min_stocks = config.get("min_stocks", 10)
        factor_weighting = config.get("factor_weights", "ic_ir")
        neutralization = config.get("neutralization", ["industry", "size"])
        weighting = config.get("weighting", "equal_weight")

        target_date = pd.Timestamp(date)

        # Step 1: Load data (252 days for factor calculation)
        date_start = target_date - pd.DateOffset(days=365)
        panel = self.load_data(universe, date_start.strftime("%Y-%m-%d"), date)
        if panel.empty:
            logger.warning(f"No data for {date}")
            return pd.Series(dtype=float)

        # Find nearest trading date in the panel
        if isinstance(panel.index, pd.MultiIndex):
            all_trading_dates = panel.index.get_level_values("date").unique().sort_values()
            trade_date = self._find_nearest_date(all_trading_dates, target_date)
        else:
            trade_date = self._find_nearest_date(panel.index.sort_values(), target_date)

        if trade_date is None:
            logger.warning(f"No trading date <= {date} in panel")
            return pd.Series(dtype=float)

        if trade_date != target_date:
            logger.debug(f"Using nearest trading date {trade_date.date()} for rebalance date {date}")

        # Step 2: Compute factor values on the full panel
        factor_df = self.registry.compute_all(panel, self.config)
        if factor_df.empty:
            logger.warning(f"No factors could be computed for {date}")
            return pd.Series(dtype=float)

        # Get factor values at the nearest trading date
        try:
            current_factors = factor_df.loc[trade_date]
        except (KeyError, TypeError):
            logger.warning(f"No factor values for {trade_date.date()} (rebalance: {date})")
            return pd.Series(dtype=float)

        # Step 3: Process and neutralize factors
        # Get cross-section data at trade_date for neutralization (if columns available)
        cross_section = panel.xs(trade_date, level="date") if isinstance(panel.index, pd.MultiIndex) else panel

        processed = {}
        for col in current_factors.columns:
            series = current_factors[col]
            if series.dropna().empty:
                continue

            # Standard processing
            series = self.processor.winsorize(series)
            series = self.processor.fill_na(series)

            # Neutralization (requires industry/market cap data in panel)
            if "industry" in neutralization and "industry" in cross_section.columns:
                industries = cross_section["industry"].reindex(series.index)
                series = self.neutralizer.neutralize_by_industry(series, industries)

            if "size" in neutralization and "total_mv" in cross_section.columns:
                mcap = cross_section["total_mv"].reindex(series.index)
                series = self.neutralizer.neutralize_by_size(series, mcap)

            # Final standardization
            series = self.processor.standardize(series)
            processed[col] = series

        if not processed:
            return pd.Series(dtype=float)

        processed_df = pd.DataFrame(processed)

        # Step 4: Combine factors
        if factor_weighting == "equal":
            weights = pd.Series(1.0 / len(processed_df.columns), index=processed_df.columns)
        elif factor_weighting == "manual":
            manual = (config.get("manual_weights") or {})
            weights = pd.Series(
                [float(manual.get(c, 0.0)) for c in processed_df.columns],
                index=processed_df.columns,
            )
            if weights.sum() <= 0:
                weights = pd.Series(1.0 / len(processed_df.columns), index=processed_df.columns)
            else:
                weights = weights / weights.sum()
        else:
            # 'ic_ir': use weights from factor evaluation; fall back to equal
            weights = self._resolve_weights(list(processed_df.columns))

        # Composite score
        composite = processed_df.mul(weights, axis=1).sum(axis=1)
        composite = composite.dropna()

        # Step 5: Select top stocks
        n_select = max(min_stocks, int(len(composite) * top_pct))
        top_stocks = composite.nlargest(n_select)

        # Step 6: Assign weights
        if weighting == "market_cap" and "total_mv" in cross_section.columns:
            mcap = cross_section["total_mv"].reindex(top_stocks.index)
            pos_weights = mcap / mcap.sum()
        else:
            pos_weights = pd.Series(1.0 / len(top_stocks), index=top_stocks.index)

        return pos_weights
